name: website

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
    # Alternative: only build for tags.
    # tags:
    #   - '*'

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.21"
          enable-cache: true

      - name: Set up Python
        run: uv python install
      - run: uv add pdoc wandb
      - name: wandb login
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: export WANDB_API_KEY="$WANDB_API_KEY"; uv run wandb login
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      # - run: pip install -e .

      - run: uv add --dev .

      - run: uv run pdoc workingmem --mermaid -o docs/

      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
